version: '3'

services:
  db:
    image: mongo
    ports: 
      - 27017:27017
  api:
    image: rafaelbenetti/native-speaker
    volumes:
      # - /home/rafaelbenetti/workspace/native-speaker:/usr/src/app
      - C:/Users/rafaelbenetti/workspace/native-speaker:/usr/src/app      
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - NODE_ENV=dev
    command: npm start