FROM node:boron

RUN mkdir -p /usr/native-speaker
WORKDIR /usr/native-speaker

COPY package.json usr/native-speaker
RUN npm install
RUN npm install nodemon -g

COPY . /usr/native-speaker

EXPOSE 3000
CMD ["nodemon", "-L", "/usr/native-speaker/src/server/server.js"]